version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fb-aws-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jkxxrqlftm9m"
s3_prefix = "fb-aws-sam"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["SentimentFunction=681261969843.dkr.ecr.us-west-2.amazonaws.com/fbawssamb394502e/sentimentfunction35d37012repo"]
